-- 집주인 동의 기반 열린 집 + 자유문구 없는 영구 집들이 방명록.
-- 기존 방은 기본 비공개로 시작하며 집주인이 직접 열어야 한다.
alter table public.rooms add column if not exists is_public boolean not null default false;

create table if not exists public.home_guestbook (
  id bigint generated by default as identity primary key,
  room_id int not null references public.rooms(id) on delete cascade,
  from_user_id uuid not null references public.profiles(id) on delete cascade,
  sticker text not null check (sticker in ('cozy','music','green','creator','pet','layout','color','welcome')),
  visit_day date not null default ((now() at time zone 'Asia/Seoul')::date),
  created_at timestamptz not null default now(),
  unique (room_id, from_user_id, visit_day)
);

alter table public.home_guestbook enable row level security;
drop policy if exists "home_guestbook_read_owner" on public.home_guestbook;
create policy "home_guestbook_read_owner" on public.home_guestbook for select using (
  exists (select 1 from public.rooms r where r.id = room_id and r.owner_id = auth.uid())
);
drop policy if exists "home_guestbook_delete_owner" on public.home_guestbook;
create policy "home_guestbook_delete_owner" on public.home_guestbook for delete using (
  exists (select 1 from public.rooms r where r.id = room_id and r.owner_id = auth.uid())
);

create or replace function public.set_room_public(p_room_id int, p_public boolean)
returns boolean language plpgsql security definer set search_path = public as $$
begin
  if auth.uid() is null then return false; end if;
  update public.rooms set is_public = p_public where id = p_room_id and owner_id = auth.uid();
  return found;
end $$;

create or replace function public.leave_home_guestbook(p_room_id int, p_sticker text)
returns text language plpgsql security definer set search_path = public as $$
declare
  uid uuid := auth.uid();
  owner uuid;
  opened boolean;
begin
  if uid is null or p_sticker not in ('cozy','music','green','creator','pet','layout','color','welcome') then return 'bad'; end if;
  select owner_id, is_public into owner, opened from public.rooms where id = p_room_id;
  if owner is null or not coalesce(opened, false) then return 'closed'; end if;
  if owner = uid then return 'self'; end if;
  insert into public.home_guestbook(room_id, from_user_id, sticker)
  values (p_room_id, uid, p_sticker)
  on conflict (room_id, from_user_id, visit_day) do nothing;
  if found then return 'ok'; end if;
  return 'today';
end $$;

-- 소유권이 바뀌면 이전 집주인의 방명록을 새 집주인에게 넘기지 않고 다시 비공개로 시작한다.
create or replace function public.reset_open_home_on_owner_change()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if old.owner_id is distinct from new.owner_id then
    delete from public.home_guestbook where room_id = old.id;
    new.is_public := false;
  end if;
  return new;
end $$;

drop trigger if exists rooms_reset_open_home on public.rooms;
create trigger rooms_reset_open_home before update of owner_id on public.rooms
for each row execute function public.reset_open_home_on_owner_change();

revoke all on function public.set_room_public(int,boolean) from public, anon;
revoke all on function public.leave_home_guestbook(int,text) from public, anon;
grant execute on function public.set_room_public(int,boolean) to authenticated;
grant execute on function public.leave_home_guestbook(int,text) to authenticated;
